spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: adminadmin
    password: qwe123!@#
    url: jdbc:postgresql://smart-utilities-db.postgres.database.azure.com:5432/postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB